import type { Metadata } from "next"
import "./globals.css"
import { AuthProvider } from "@/context/AuthContext"
import MobileNavbar from "@/components/mobile-navbar"

export const metadata: Metadata = {
  title: "Zillagram",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
          <MobileNavbar />
          </AuthProvider>
      </body>
    </html>
  )
}
